version: 2
project_name: tk

# Note: UI bundle is built by GitHub Actions workflow before goreleaser runs.
# For local releases, run ./scripts/build-ui.sh first.

before:
  hooks:
    - go mod tidy

builds:
  - id: tk
    main: ./cmd/tk
    binary: tk
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: pengelbrecht
    name: ticks
  draft: false
  prerelease: auto
